### PR TITLE
Update kubeval formula to 0.7.3

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by fhemberger** [comment]
Is there an easy way to automate the update process? Like triggering a GitHub action on every `kubeval` release to update the formula as well?

**Comment by fhemberger** [comment]
Something like this in kubeval's `.travis.yml` should do the trick:

```yaml
script: 
  - export SHA256="$(sha256sum releases/kubeval-darwin-amd64.tar.gz | cut -d ' ' -f 1)"
  - git clone https://github.com/garethr/homebrew-kubeval.git
  - cd homebrew-kubeval
  - sed -i -E "s|download/[^/]+|download/$TRAVIS_TAG|; s|sha256 \"[^\"]+|sha256 \"$SHA256|; s|version \"[^\"]+|version \"$TRAVIS_TAG|" Formula/kubeval.rb
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m "Release $TRAVIS_TAG"
  - git push -f -q https://${GH_TOKEN}@github.com/garethr/homebrew-kubeval.git master
``` 

Build failure seems to have been a Travis CI hiccup. Running it again should fix it.

**Comment by fhemberger** [comment]
@garethr Is it okay to merge this? Homebrew still installs the old version at the moment. 🤗

**Comment by garethr** [comment]
@fhemberger thanks.

**Pull request merged**
